language: cpp
matrix:
   include:
    - os: linux
      compiler: gcc
      env: JULIAVERSION="juliareleases"
    - os: linux
      compiler: gcc
      env: JULIAVERSION="julianightlies"
    - os: osx
      compiler: gcc
      env: JULIAVERSION="juliareleases"
    - os: osx
      compiler: gcc
      env: JULIAVERSION="julianightlies"
notifications:
    email: false
before_install:
    - curl http://julialang.org/install-julia.sh | sh -s $JULIAVERSION
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'versioninfo()'
script:
    - julia -e 'Pkg.init(); Pkg.clone(pwd())'
    - julia -e 'Pkg.test("HttpServer", coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("HttpServer")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
